export default {
  lang: {
    locale: "en_US",
    placeholder: "Select date",
    rangePlaceholder: ["Эхлэх огноо", "Дуусах огноо"],
    today: "Өнөөдөр",
    now: "Одоо",
    backToToday: "Өнөөдрийг сонгох",
    ok: "OK",
    clear: "Цэвэрлэх",
    month: "Сар",
    year: "Жил",
    timeSelect: "Цаг сонгох",
    dateSelect: "Огноо сонгох",
    monthSelect: "Сар сонгох",
    yearSelect: "Жил сонгох",
    decadeSelect: "Choose a decade",
    yearFormat: "YYYY",
    dateFormat: "M/D/YYYY",
    dayFormat: "D",
    dateTimeFormat: "M/D/YYYY HH:mm:ss",
    monthFormat: "MMMM",
    monthBeforeYear: true,
    previousMonth: "Өмнөх сар (PageUp)",
    nextMonth: "Дараах сар (PageDown)",
    previousYear: "Өмнөх жил (Control + left)",
    nextYear: "Дараах жил (Control + right)",
    previousDecade: "Last decade",
    nextDecade: "Next decade",
    previousCentury: "Last century",
    nextCentury: "Next century",
    shortMonths: [
      "1-р сар",
      "2-р сар",
      "3-р сар",
      "4-р сар",
      "5-р сар",
      "6-р сар",
      "7-р сар",
      "8-р сар",
      "9-р сар",
      "10-р сар",
      "11-р сар",
      "12-р сар",
    ],
  },
  timePickerLocale: {
    placeholder: "огноо сонгох",
  },
  dateFormat: "YYYY-MM-DD",
  dateTimeFormat: "YYYY-MM-DD HH:mm:ss",
  weekFormat: "YYYY-wo",
  monthFormat: "YYYY-MM",
};
